### ISSUE TITLE
TODO before InnoDay

### ISSUE THREAD

**Issue by Justrebl** [ikhemissi/azure-ipaas-workshop#23]
### Introduction 

- [ ] Explicit a way of using the Rest Client that do not require any sign in (compared to the Postman option).
- [ ] Add a reference to this Http tooling section in each task that requests an http call.
- [ ] Missing postman instructions : 
- [ ] Postman screenshots from vscode extension
- [ ] Add an 👨‍🎓 instructor led instruction in the introduction : explain some steps won’t need to be done as they are done or will be given credentials for them

### Lab 1
- [x] Configure the Create or update item action to create a new document in CosmosDB in Logic App loa-proc-lab-no-ipa-[randomId] workflow `wf_orders_from_sb_to_cdb.
- [x] Opérations/actions/functions <= All the ops/functions in Logic Apps are called Actions (uniformiser)
- [x] Tasks lab 1 a finaliser <= Expliciter
- [ ] Add a quick Summary to lab 1 <= Just like lab 2 an 3

### Lab 2
- [x] You have to edit the code locally (not in Azure portal). <= in the codespace
- [x] + précisions on where to apply changes in the code/folder
- [x] re-deploy the Function App code to get your updates running on Azure: <= from the codespace terminal run the following command
- [ ] #26
- [x] Clixk on the FetchOrdes <= typo
- [x] You can take any URL because for this lab, we disabled the key<=  Trop complexe

### Lab 3
- [x] Go the Azure APIM (name should start with apim-lab-no-ipa) <= consistence dans le naming avec [randomid]
- [ ] Add a Little explanation on what will be done in Lab 3
- [ ] What is APIM
- [ ] Add laïus on API/products in APIM
- [x] We will know test our API with the subscription key. <= Now
- [ ] The result of this test is negative. A 401 Access Denied error is returned by the APIM. The error message states that the subscription key is missing.
- [x] will now see how to securize our API with the OAuth 2.0 standard <= secure
- [x] Instructor led warning to get out of the toggle
- [ ] Laïus on app registration.
- [ ] TBD : how we get the tenant ?? <=  Add an instructor led instruction on this tab
- [x] OAuth 2.0 framework! <= protocole
- [ ] begin, we will set a limit for the Basic user to ensur <= as it represents a free usage of our api
- [x] Go back to Postman and run about ten closely spaced tests. <= Call it 6 Times to trigger the rate limiting policy
- [ ] ❗Clarify the ToggleSolutions to explain how to run tests, and how to retrieve the URLs to contact from the APIM interface
- [ ] Add Instructions on where to get the URL to call for the APIM policy tests
- [x] Go back to Postman and run about a test and observe the result. And send one http request
- [x] Once you're done with this lab you can delete all the resources which you have created at the beginning using the following command: <= from the codespace environnement, run azd down

**Comment by lgmorand** [comment]
pour moi pour l'intro, je me ferais pas trop chier. si on laisse chacun utiliser l'outil de son choix, on n'a pas à les guider particulierement. et si le mec ne sait pas faire une requete HTTP, je sais pas s'il doit faire le lab.

j'ai fix le lab1 et un bout du lab3 apres le travail de lulu et iheb

**Comment by Justrebl** [comment]
On peut effectivement ne pas rentrer dans ce niveau de détail, mais j'ai eu des cas (à chaque lab) où les gars savaient pas taper une commande az cli et remplacer des placeholders :) 
Je me méfie à chaque fois maintenant.
